name: HIT Test Pipeline

on:
  push:
  pull_request:

jobs:

  test-hits:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        hit: [HIT 1, HIT 2, HIT 3, HIT 4, HIT 5, HIT 6, HIT 7, HIT 8]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then
            pip install -r requirements.txt
            fi

      - name: Run HIT test
        run: |
          echo "Running test for ${{ matrix.hit }}"
          python "${{ matrix.hit }}/Tests/${{ matrix.hit }}_Test.py"